before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
language: node_js
node_js:
  - "node"
  - "lts/*"
  - "6"
install:
  - npm install react@^16.0.0 --no-save
  - npm install
  - npm run compile
  - npm run dist
env:
  - TEST_SUBJECT=src
  - TEST_SUBJECT=lib
  - TEST_SUBJECT=dist
matrix:
  exclude:
  - node_js: 6
    env: TEST_SUBJECT=src
